INSERT INTO descricao_procedimento VALUES (23445, 'Remoção de feto vivo. Incisão transversal');
INSERT INTO descricao_procedimento VALUES (39485, 'Desobstruçao da artéria coronária devido a placas de gordura. Utilizando stent de aço');
INSERT INTO descricao_procedimento VALUES (96984, 'Remoção do apêndice inflamado');
INSERT INTO descricao_procedimento VALUES (12435, 'Remoção de calculo renal coraliformes');
INSERT INTO descricao_procedimento VALUES (37654, 'Craniotomia para remoção de tumor do 4º ventriculo cerebral');
INSERT INTO descricao_procedimento VALUES (95845, 'Registro da variação dos potenciais elétricos gerados pela atividade elétrica do coração.');
INSERT INTO descricao_procedimento VALUES (89273, 'Hematócrito, Hemoglobina, Leucograma, Colesterol e Plasma sanguineo');
INSERT INTO descricao_procedimento VALUES (49853, '-');
INSERT INTO descricao_procedimento VALUES (76472, 'Hematócrito, Hemoglobina, Leucograma, Colesterol e Plasma sanguineo');
INSERT INTO descricao_procedimento VALUES (56786, '-');
INSERT INTO descricao_procedimento VALUES (92738, 'Tomografia computadorizada transversal craniana');
INSERT INTO descricao_procedimento VALUES (24805, 'Registro da variação dos potenciais elétricos gerados pela atividade elétrica do coração.');
INSERT INTO descricao_procedimento VALUES (43573, 'Hematócrito, Hemoglobina, Leucograma, Colesterol e Plasma sanguineo');
INSERT INTO descricao_procedimento VALUES (73859, '-');
INSERT INTO descricao_procedimento VALUES (68933, 'Hematócrito, Hemoglobina, Leucograma, Colesterol e Plasma sanguineo');
INSERT INTO descricao_procedimento VALUES (86231, 'Amostragem do revestimento do colo do útero');
INSERT INTO descricao_procedimento VALUES (96732, 'Tratamento da ectopia de colo de útero');
INSERT INTO descricao_procedimento VALUES (34783, 'Registro da variação dos potenciais elétricos gerados pela atividade elétrica do coração.');
INSERT INTO descricao_procedimento VALUES (28792, 'Hematócrito, Hemoglobina, Leucograma, Colesterol e Plasma sanguineo');
INSERT INTO descricao_procedimento VALUES (56235, 'Amostragem da pressão arterial durante 24horas');
INSERT INTO descricao_procedimento VALUES (26381, 'Hematócrito, Hemoglobina, Leucograma, Colesterol e Plasma sanguineo');
INSERT INTO descricao_procedimento VALUES (87361, 'Imagens do fêmur e úmero esquerdo');
INSERT INTO descricao_procedimento VALUES (16749, 'Imobilização do femur esquerdo. Gesso tipo IV. Duração de 2 meses');
INSERT INTO descricao_procedimento VALUES (82749, 'Elementos anormais do sedimento e urocultura');
INSERT INTO descricao_procedimento VALUES (72940, '-');
INSERT INTO descricao_procedimento VALUES (26489, 'Elementos anormais do sedimento e urocultura');
INSERT INTO descricao_procedimento VALUES (32789, 'Angioressonância Cerebral tranversal');
INSERT INTO descricao_procedimento VALUES (98102, 'Hematócrito, Hemoglobina, Leucograma, Colesterol e Plasma sanguineo');
INSERT INTO descricao_procedimento VALUES (72136, 'Quimioterapia adjuvante. Ciclofosfamida e Trimetoprim. Administração intravenosa');
INSERT INTO descricao_procedimento VALUES (87392, 'Quimioterapia adjuvante. Ciclofosfamida e Trimetoprim. Administração intravenosa');
