INSERT INTO descricao_enfermidade  VALUES (1, 'Inflamação do canal médio do ouvido. Causa bacteriana');
INSERT INTO descricao_enfermidade  VALUES (2, 'Inflamação dos sinos faciais');
INSERT INTO descricao_enfermidade  VALUES (3, 'Ingestão de alimento ou agua contaminado por bacteria ou microbio não parasitoide');
INSERT INTO descricao_enfermidade  VALUES (4, 'Ataque cardiaco. Entupimento da artéria cardiaca');
INSERT INTO descricao_enfermidade  VALUES (5, 'Envenenamento por picada de reptiliano');
INSERT INTO descricao_enfermidade  VALUES (6, 'Fratura no úmero');
INSERT INTO descricao_enfermidade  VALUES (7, 'Deslocamento da vertebra c2 causada por trauma. Compressão no nervo cervical');
INSERT INTO descricao_enfermidade  VALUES (8, '-');
INSERT INTO descricao_enfermidade  VALUES (9, 'Gripe A. Tipo Influenza');
INSERT INTO descricao_enfermidade  VALUES (10, 'Grupo de doenças que inclui angina estável e angina instável');
INSERT INTO descricao_enfermidade  VALUES (11, 'Inflamação dos alvéolos pulmonares. Causada por infecção bacteriana');
INSERT INTO descricao_enfermidade  VALUES (12, 'Inflamação do trato respiratório primario. Causada por infecção viral ou bacteriana');
INSERT INTO descricao_enfermidade  VALUES (13, 'Inflamação da membrana conjuntiva e da superfície interior da pálpebra');
INSERT INTO descricao_enfermidade  VALUES (14, 'Doença altamente contagiosa causada pelo vírus do sarampo.');
INSERT INTO descricao_enfermidade  VALUES (15, 'Problemas na irrigação sanguínea cérebro causam a morte das células, o que faz com que partes do cérebro deixem de funcionar devidamente. Inlcui dois tipos principais: isquémico ou hemorrágico');
INSERT INTO descricao_enfermidade  VALUES (16, 'Inflamação do apêndice');
INSERT INTO descricao_enfermidade  VALUES (17, 'Urolitíase, massa ou agregado cristalino sólido que se forma nos rins a partir de sais minerais presentes na urina');
INSERT INTO descricao_enfermidade  VALUES (18, 'Doença inflamatória crónica das vias aéreas');
INSERT INTO descricao_enfermidade  VALUES (19, 'Ependinoma no 4º ventrículo cerebral');
INSERT INTO descricao_enfermidade  VALUES (20, 'Hemorragia inntrauteriana. Causa desconhecida');
