INSERT INTO public.enfermidade    VALUES (1, 'Otite');
INSERT INTO public.enfermidade    VALUES (2, 'Sinusite');
INSERT INTO public.enfermidade    VALUES (3, 'Intoxicação alimentar');
INSERT INTO public.enfermidade    VALUES (4, 'Infarto do Miocardio');
INSERT INTO public.enfermidade    VALUES (5, 'Picada de cobra');
INSERT INTO public.enfermidade    VALUES (6, 'Perna quebrada');
INSERT INTO public.enfermidade    VALUES (7, 'Deslocamento da vertebra c2');
INSERT INTO public.enfermidade    VALUES (8, 'Trabalho de parto');
INSERT INTO public.enfermidade    VALUES (9, 'Gripe h1n1');
INSERT INTO public.enfermidade    VALUES (10, 'Doença arterial coronária');
INSERT INTO public.enfermidade    VALUES (11, 'Pneumonia');
INSERT INTO public.enfermidade    VALUES (12, 'Faringite');
INSERT INTO public.enfermidade    VALUES (13, 'Conjuntivite');
INSERT INTO public.enfermidade    VALUES (14, 'Sarampo');
INSERT INTO public.enfermidade    VALUES (15, 'Ataque vascular cerebral');
INSERT INTO public.enfermidade    VALUES (16, 'Apendicite');
INSERT INTO public.enfermidade    VALUES (17, 'Pedra no rim');
INSERT INTO public.enfermidade    VALUES (18, 'Asma');
INSERT INTO public.enfermidade    VALUES (19, 'Tumor no cérebro');
INSERT INTO public.enfermidade    VALUES (20, 'Hemorragia interna');
